"use client";
import { Pencil, X } from "lucide-react";
import { money, dateText } from "@/lib/data";

const Pair=({label,value}:{label:string,value:any})=><div><span>{label}</span><b>{value===undefined||value===null||value===""?"—":String(value)}</b></div>;
export default function ReportModal({data,onClose}:{data:any,onClose:()=>void}){
  if(!data)return null;
  const purchasing=data.type==="purchasing";
  const title=purchasing?data.order?.order_id:data.job?.job_no;
  const people=data.people||[];
  const serviceEditHref=(()=>{
    if(purchasing||typeof window==="undefined"||!data.links?.form)return "";
    const host=window.location.hostname;
    const office=host==="localhost"||host==="127.0.0.1"||host.startsWith("10.")||host.startsWith("192.168.")||/^172\.(1[6-9]|2\d|3[01])\./.test(host)||/^100\.(6[4-9]|[7-9]\d|1[01]\d|12[0-7])\./.test(host)||!host.includes(".");
    return office?`${window.location.protocol}//${host}:5055${data.links.form}`:"";
  })();
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal">
    <div className="modal-head"><div><b>{title||"Report output"}</b><span className="sub">{purchasing?"Purchasing form report":"Servicing form report"}</span></div><div className="row-actions">{serviceEditHref&&<a className="btn primary" href={serviceEditHref} target="_blank" rel="noreferrer"><Pencil/>Edit Service Form</a>}<button className="btn" onClick={onClose}><X/>Close</button></div></div>
    <div className="modal-body">
      {purchasing?<>
        <section className="detail-section"><h3>Order output</h3><div className="detail-grid"><Pair label="Customer" value={data.order?.customer_name}/><Pair label="Branch" value={data.order?.branch}/><Pair label="Status" value={data.order?.status}/><Pair label="Marketing person" value={data.order?.marketing_person}/><Pair label="Quote no" value={data.order?.quote_no}/><Pair label="Updated" value={dateText(data.order?.updated_at)}/></div></section>
        <section className="detail-section"><h3>Financial output</h3><div className="detail-grid"><Pair label="Order value" value={money(data.financials?.order_value)}/><Pair label="Received" value={money(data.financials?.received)}/><Pair label="Outstanding" value={money(data.financials?.outstanding)}/><Pair label="Purchase cost" value={money(data.financials?.purchase_cost)}/><Pair label="Selling cost" value={money(data.financials?.selling_cost)}/><Pair label="Profit" value={money(data.financials?.profit)}/><Pair label="Profit %" value={`${data.financials?.profit_percentage||0}%`}/><Pair label="Supplier bill" value={money(data.financials?.supplier_bill)}/><Pair label="Supplier balance" value={money(data.financials?.supplier_balance)}/></div></section>
        <section className="detail-section"><h3>Purchasing workflow output</h3><div className="detail-grid"><Pair label="Delivery period" value={data.order?.delivery_period}/><Pair label="Terms" value={data.order?.terms}/><Pair label="Order placed to" value={data.order?.order_place_to}/><Pair label="Dispatch by" value={data.dispatch?.packing_by}/><Pair label="Dispatch date" value={data.dispatch?.dispatch_on}/><Pair label="Courier / mode" value={data.dispatch?.courier_mode}/><Pair label="Accounts signature" value={data.accounts?.signature}/><Pair label="Approved by" value={data.order?.approved_by}/><Pair label="Approval date" value={data.order?.approval_date}/></div></section>
      </>:<>
        <section className="detail-section"><h3>Service job output</h3><div className="detail-grid"><Pair label="Customer" value={data.customer?.name}/><Pair label="Branch" value={data.job?.branch}/><Pair label="Status" value={data.job?.status}/><Pair label="Job date" value={data.job?.job_date}/><Pair label="Office type" value={data.job?.office_type}/><Pair label="Updated" value={dateText(data.job?.updated_at)}/></div></section>
        <section className="detail-section"><h3>Service value</h3><div className="detail-grid"><Pair label="Product value" value={money(data.totals?.product_value)}/><Pair label="Repair estimate" value={money(data.totals?.repair_estimate)}/><Pair label="Discount" value={money(data.totals?.discount)}/><Pair label="Total estimate" value={money(data.totals?.total_estimate)}/><Pair label="Payment mode" value={data.payment?.mode||data.payment?.paymentMode}/><Pair label="Receipt mode" value={data.receipt?.mode||data.receipt?.receiptMode}/></div></section>
        <section className="detail-section"><h3>Service workflow output</h3><div className="detail-grid"><Pair label="Receipt reference" value={data.receipt?.reference||data.receipt?.receiptReference}/><Pair label="Courier / receipt" value={data.receipt?.courier||data.receipt?.courierName}/><Pair label="Dispatch mode" value={data.dispatch?.mode||data.dispatch?.dispatchMode}/><Pair label="Dispatch reference" value={data.dispatch?.reference||data.dispatch?.referenceNo}/><Pair label="Tested by" value={data.dispatch?.testedBy}/><Pair label="Payment received by" value={data.payment?.receivedBy}/><Pair label="Email status" value={data.communication?.email?.status||data.communication?.emailStatus}/><Pair label="WhatsApp status" value={data.communication?.whatsapp?.status||data.communication?.whatsappStatus}/><Pair label="Notes" value={data.job?.notes}/></div></section>
      </>}
      <section className="detail-section"><h3>Who worked on this process</h3><div className="process-grid">{people.map((p:any,i:number)=><div className={`process-box ${p.completed?"done":""}`} key={i}><span>{p.stage||p.role_detail}</span><b>{p.person||"Not recorded"}</b><small>{p.role_detail||""}{p.updated_at?` • ${dateText(p.updated_at)}`:""}</small></div>)}</div></section>
      {purchasing&&Array.isArray(data.products)&&<section className="detail-section"><h3>Products</h3><div className="table-wrap"><table className="table"><thead><tr><th>Product</th><th>Model / Make</th><th>Qty</th><th>Value</th></tr></thead><tbody>{data.products.map((p:any,i:number)=><tr key={i}><td><b>{p.item_name||p.product_name||p.product||p.description||"Product"}</b></td><td>{p.model||p.make||p.brand||"—"}</td><td>{p.qty||p.quantity||"—"}</td><td className="money">{money(p.total||p.item_value||p.amount||p.value||0)}</td></tr>)}</tbody></table></div></section>}
      {purchasing&&Array.isArray(data.customer_payments)&&data.customer_payments.length>0&&<section className="detail-section"><h3>Customer payments</h3><div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>Mode / Bank</th><th>Amount</th></tr></thead><tbody>{data.customer_payments.map((x:any,i:number)=><tr key={i}><td>{x.payment_date||"—"}</td><td>{x.bank_mode||x.mode||"—"}</td><td className="money">{money(x.amount)}</td></tr>)}</tbody></table></div></section>}
      {purchasing&&Array.isArray(data.suppliers)&&data.suppliers.length>0&&<section className="detail-section"><h3>Supplier output</h3><div className="table-wrap"><table className="table"><thead><tr><th>Supplier</th><th>Product / Details</th><th>Amount</th><th>Status</th></tr></thead><tbody>{data.suppliers.map((x:any,i:number)=><tr key={i}><td><b>{x.supplier_name||x.supplier||x.company||"—"}</b></td><td>{x.product_name||x.item_name||x.details||x.remarks||"—"}</td><td className="money">{money(x.total||x.amount||x.price||0)}</td><td>{x.status||x.payment_status||"—"}</td></tr>)}</tbody></table></div></section>}
      {!purchasing&&Array.isArray(data.products)&&<section className="detail-section"><h3>Products / repair output</h3><div className="table-wrap"><table className="table"><thead><tr><th>Product</th><th>Model</th><th>Complaint / problem</th><th>Estimate</th></tr></thead><tbody>{data.products.map((p:any,i:number)=><tr key={i}><td><b>{p.productName||p.name||"Product"}</b></td><td>{p.makeModel||p.model||"—"}</td><td>{p.complaint||p.problem||p.serviceProblem||"—"}</td><td className="money">{money(p.repairEstimate||p.repairPrice||p.estimate||0)}</td></tr>)}</tbody></table></div></section>}
    </div>
  </div></div>;
}
